pipeline:
  name: Manohar_Build_pipeline
  identifier: Manohar_Build_pipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: GradleBuild
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: ./gradlew clean build
              - step:
                  type: Run
                  name: Show Folders
                  identifier: Show_Folders
                  spec:
                    shell: Sh
                    command: |-
                      ls -a
                      ls -a build
                      ls -a build/libs
              - step:
                  type: BuildAndPushDockerRegistry
                  name: PublishDockerImage
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: mdavireddydocker
                    repo: mdavireddy/rest-service
                    tags:
                      - <+pipeline.sequenceId>
                    runAsUser: "0"
        delegateSelectors:
          - helm-delegate
  notificationRules:
    - name: webhook-notification
      identifier: webhooknotification
      pipelineEvents:
        - type: AllEvents
        - type: PipelineStart
        - type: PipelineEnd
        - type: PipelineSuccess
        - type: PipelineFailed
        - type: StageFailed
        - type: StageSuccess
        - type: StageStart
        - type: StepFailed
      notificationMethod:
        type: Webhook
        spec:
          webhookUrl: https://empmanuutah.service-now.com/api/sn_devops/v2/devops/tool/orchestration?toolId=31f9084b1babb110c5c686a3604bcbd6&token=<+secrets.getValue("empmanuutahtoken")>
      enabled: true
  properties:
    ci:
      codebase:
        connectorRef: ManoharGithub
        repoName: rest-service
        build: <+input>
  delegateSelectors:
    - helm-delegate
