pipeline:
  envVariables:
    WEBHOOK_TOKEN: <+secrets.getValue("empmanuutahtoken")>
  name: Manohar_Build_pipeline
  identifier: Manohar_Build_pipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo 'hello'
                          echo ht686a3604bcbd6&token=<+secrets.getvalue("empmanuutahtoken")>
                          echo 'base64'
                          echo <+secrets.getValue("empmanuutahtoken")> | base64

                          echo ${environmentVariable.WEBHOOK_TOKEN}  
                    environmentVariables: []
                    outputVariables: []
                    delegateSelectors:
                      - kubernetes-delegate
                  timeout: 10m
        tags: {}
  notificationRules:
    - name: webhook-notification
      identifier: webhooknotification
      pipelineEvents:
        - type: AllEvents
        - type: PipelineStart
        - type: PipelineEnd
        - type: PipelineSuccess
        - type: PipelineFailed
        - type: StageFailed
        - type: StageSuccess
        - type: StageStart
        - type: StepFailed
      notificationMethod:
        type: Webhook
        spec:
          webhookUrl: <+secrets.getValue("empmanuutahtoken")>
      enabled: true
  properties:
    ci:
      codebase:
        connectorRef: ManoharGithub
        repoName: rest-service
        build: <+input>
