pool:
  vmImage: ubuntu-latest

trigger:
  branches:
    include: 
    - main


steps:
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'MyArtifact'
    publishLocation: 'pipeline'
