name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  SNOW_URL: ${{ secrets.SNOW_URL }}
  SNOW_TOKEN: ${{ secrets.SNOW_TOKEN }}
  SNOW_TOOLID: ${{ secrets.SNOW_TOOLID }}
  CI_PIPELINE_ID: ${{ github.run_id }}
  CI_API_V4_URL: ${{ github.server_url }}
  CI_JOB_ID: ${{ github.run_id }}
  CI_PROJECT_PATH: ${{ github.job }}
  CI_REPOSITORY_NAME: ${{ github.repository }}
  CI_RUN_ATTEMPT: ${{ github.run_attempt }}
  CI_PROJECT_ID: ${{ github.run_id }}
  CI_PROJECT_TITLE: ${{github.repository}}/${{github.workflow}}
  CI_COMMIT_BRANCH: $${{github.ref_name }}
  CI_WORKFLOW_NAME: ${{ github.workflow }}

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - name: Pre-Build Step
        run: echo ${{ github.job }}

  changeapproval:
    runs-on: ubuntu-latest
    #container:
      #  image: mdavireddy/sndevops:2.0.0
    env:
      CHG_JOB_ID: ${{ github.run_id }}
    steps:
      - name: Create Change Request
        run: |
          echo "CHG_JOB_ID=${{ github.run_id }}"
        #  sndevopscli create change -p "{\"changeStepDetails\":{\"timeout\":3600,\"interval\":100},\"autoCloseChange\":true,\"attributes\":{\"short_description\":\"G Venkata Automated Software Deployment\",\"description\":\"Automated Software Deployment.\",\"assignment_group\":\"a715cd759f2002002920bde8132e7018\",\"implementation_plan\":\"Software update is tested and results can be found in Test Summaries Tab.\",\"backout_plan\":\"When software fails in production, the previous software release will be re-deployed.\",\"test_plan\":\"Testing if the software was successfully deployed or not\"}}"
        #  sndevopscli get change

  getchange:
    runs-on: ubuntu-latest
    needs: changeapproval
    #container:
       #  image: mdavireddy/sndevops:2.0.0
    steps:
      - name: Get Change Request
        run: |
           echo "CHG_JOB_ID=${{ github.run_id }}"
          # sndevopscli get change -p "{\"buildNumber\":${CHG_JOB_ID},\"stageName\":\"ServiceNow DevOps Change Step\",\"pipelineName\":\"SmrutiTestDemoProject\"}"


  updatechange:
    runs-on: ubuntu-latest
    needs: getchange
  #  container:
       #  image: mdavireddy/sndevops:2.0.0
    steps:
      - name: Update Change Request
        run: |
         echo "CHG_JOB_ID=${{ github.run_id }}"
         # sndevopscli update change -p "{\"short_description\":\"Updated Automated Software Deployment\",\"description\":\"Automated Software Deployment.\",\"assignment_group\":\"xxxxxxx\",\"implementation_plan\":\"Software update is tested and results can be found in Test Summaries Tab.\",\"backout_plan\":\"When software fails in production, the previous software release will be re-deployed.\",\"test_plan\":\"Testing if the software was successfully deployed or not\"}"

  deploy:
    runs-on: ubuntu-latest
    needs: updatechange
    steps:
      - name: Deploy Job
        run: echo ${{ github.job }}
        
  ScanResults:
    runs-on: ubuntu-latest
    needs: deploy
    container:
      image: mdavireddy/sndevops:2.0.0
    steps:
      - name: Update Change Request
        run: |
           sndevopscli create securityScan -p "{ \"pipelineInfo\": {  \"buildNumber\": \"${{ github.run_id }}\",   \"pipelineExecutionUrl\": \"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}, \"securityResultAttributes\": { \"scanner\": \"Veracode\",    \"applicationName\": \"PetStoreAPI-Github\",\"buildVersion\": \"\",   \"securityToolId\: \"\"}}"

       
