name: Java CI with Gradle

on:
  #workflow_call:
   push:
     branches: [ "main" ]

env:
  SNOW_URL: ${{ secrets.SNOW_URL }}
  SNOW_TOKEN: ${{ secrets.SNOW_TOKEN }}
  SNOW_TOOLID: ${{ secrets.SNOW_TOOLID }}
  CI_PIPELINE_ID: ${{ github.run_id }}
  CI_API_V4_URL: ${{ github.server_url }}
  CI_JOB_ID: ${{ github.run_id }}
  CI_PROJECT_PATH: ${{ github.job }}
  CI_REPOSITORY_NAME: ${{ github.repository }}
  CI_RUN_ATTEMPT: ${{ github.run_attempt }}
  #CI_PROJECT_ID: ${{ github.run_id }}
  CI_PROJECT_TITLE: ${{github.repository}}/${{github.workflow}}
  CI_COMMIT_BRANCH: $${{github.ref_name }}
  CI_WORKFLOW_NAME: ${{ github.workflow }}

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - name: Pre-Build Step
        run: echo ${{ github.job }}

  changeapproval:
    runs-on: ubuntu-latest
    container:
      image: mdavireddy/sndevops:2.0.0
    env:
      CI_JOB_NAME: changeapproval
    steps:
      - name: Create Change Request
        run: |
          echo "CHG_JOB_ID=${{ github.run_id }}"
          sndevopscli create change -ctx "{\"projectId\": \"123456\"}" -p "{\"changeStepDetails\": {\"timeout\":3600,\"interval\":100},\"autoCloseChange\":true,\"attributes\":{\"short_description\":\"G Venkata Automated Software Deployment\",\"description\":\"Automated Software Deployment.\",\"assignment_group\":\"a715cd759f2002002920bde8132e7018\",\"implementation_plan\":\"Software update is tested and results can be found in Test Summaries Tab.\",\"backout_plan\":\"When software fails in production, the previous software release will be re-deployed.\",\"test_plan\":\"Testing if the software was successfully deployed or not\"}}"

  getchange:
    runs-on: ubuntu-latest
    needs: changeapproval
    container:
      image: mdavireddy/sndevops:2.0.0
    env:
      CI_JOB_NAME: getchange   
    steps:
      - name: Get Change Request
        run: |
           sndevopscli get change -p "{\"buildNumber\":\"${{ github.run_id }}\",\"stageName\":\"changeapproval\",\"pipelineName\":\"${{github.repository}}/${{github.workflow}}\", \"attemptNumber\": \"${{ github.run_attempt }}\"}"


  
  deploy:
    runs-on: ubuntu-latest
    needs: getchange
    steps:
      - name: Deploy Job
        run: echo ${{ github.job }}
        
  ScanResults:
    runs-on: ubuntu-latest
    needs: deploy
    container:
      image: mdavireddy/sndevops:2.0.0
    steps:
      - name: Update Change Request
        run: |
            echo "hello"
           #sndevopscli create securityScan -p "{ \"pipelineInfo\": {  \"runId\": \"${{ github.run_id }}\",   \"runNumber\": \"${{ github.run_number }}\", \"runAttempt\": \"${{ github.run_attempt }}\",   \"job\": \"ServiceNowDevOpsSecurityScan\",  \"workflow\": \"${{ github.workflow }}\",  \"repository\": \"${{github.repository}}\" }, \"securityResultAttributes\": { \"scanner\": \"Veracode\",    \"applicationName\": \"PetStoreAPI-Github\",\"buildVersion\": \"\",   \"securityToolId\": \"\"}}"
