name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
env:
  SNOW_URL: ${{ secrets.SNOW_URL }}
  SNOW_TOKEN: ${{ secrets.SNOW_TOKEN }}
  SNOW_TOOLID: ${{ secrets.SNOW_TOOLID }}
  CI_PIPELINE_ID: ${{ github.run_id }}
  CI_API_V4_URL: ${{ github.server_url }}
  CI_JOB_ID: ${{ github.run_id }}
  CI_PROJECT_PATH: ${{ github.job }}
  CI_REPOSITORY_NAME: ${{ github.repository }}
  CI_RUN_ATTEMPT: ${{ github.run_attempt }}
  CI_PROJECT_ID: ${{ github.run_id }}
  CI_PROJECT_TITLE: ${{github.repository}}/${{github.workflow}}
  CI_COMMIT_BRANCH: $${{github.ref_name}}
  CI_WORKFLOW_NAME: ${{ github.workflow }}

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - name: Pre-Build Step
        run: echo ${{ github.job }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker container
        uses: actions/checkout@v2
      - name: Build Artifact and Package
        run: |
          docker run --rm servicenowdocker/sndevops:4.1.0 sndevopscli create artifact -a "[{\"name\":\"Artifact-${{ github.job }}\",\"repositoryName\":\"TestRepo\",\"version\":\"1.${{ github.run_id }}.0\"}]"
          docker run --rm servicenowdocker/sndevops:4.1.0 sndevopscli create package -n "Test_Package" -a "[{\"name\":\"Artifact-${{ github.job }}\",\"repositoryName\":\"TestRepo\",\"version\":\"1.${{ github.run_id }}.0\"}]"

  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: ServiceNow DevOps SonarScan Results
        run: docker run --rm servicenowdocker/sndevops:4.1.0 sndevopscli create sonar -url 'https://sonarcloud.io' -projectKey 'xxxxxxx'

  changeapproval:
    runs-on: ubuntu-latest
    env:
      CHG_JOB_ID: ${{ github.run_id }}
    steps:
      - name: Create Change Request
        run: |
          echo "CHG_JOB_ID=${{ github.run_id }}" >> generated_job_id.env
          docker run --rm servicenowdocker/sndevops:4.1.0 sndevopscli create change -p "{\"changeStepDetails\":{\"timeout\":3600,\"interval\":100},\"autoCloseChange\":true,\"attributes\":{\"short_description\":\"G Venkata Automated Software Deployment\",\"description\":\"Automated Software Deployment.\",\"assignment_group\":\"a715cd759f2002002920bde8132e7018\",\"implementation_plan\":\"Software update is tested and results can be found in Test Summaries Tab.\",\"backout_plan\":\"When software fails in production, the previous software release will be re-deployed.\",\"test_plan\":\"Testing if the software was successfully deployed or not\"}}"
          docker run --rm servicenowdocker/sndevops:4.1.0 sndevopscli get change
      - name: Upload generated_job_id.env
        uses: actions/upload-artifact@v2
        with:
          name: generated_job_id
          path: generated_job_id.env

  getchange:
    runs-on: ubuntu-latest
    needs: changeapproval
    steps:
      - name: Download generated_job_id.env
        uses: actions/download-artifact@v2
        with:
          name: generated_job_id
      - name: Get Change Request
        run: |
          source generated_job_id.env
          docker run --rm servicenowdocker/sndevops:4.1.0 sndevopscli get change -p "{\"buildNumber\":${CHG_JOB_ID},\"stageName\":\"ServiceNow DevOps Change Step\",\"pipelineName\":\"SmrutiTestDemoProject\"}"
      - name: Upload sndevopschg.json
        uses: actions/upload-artifact@v2
        with:
          name: sndevopschg
          path: sndevopschg.json

  updatechange:
    runs-on: ubuntu-latest
    needs: getchange
    steps:
      - name: Update Change Request
        run: docker run --rm servicenowdocker/sndevops:4.1.0 sndevopscli update change -p "{\"short_description\":\"Updated Automated Software Deployment\",\"description\":\"Automated Software Deployment.\",\"assignment_group\":\"xxxxxxx\",\"implementation_plan\":\"Software update is tested and results can be found in Test Summaries Tab.\",\"backout_plan\":\"When software fails in production, the previous software release will be re-deployed.\",\"test_plan\":\"Testing if the software was successfully deployed or not\"}"

  deploy:
    runs-on: ubuntu-latest
    needs: updatechange
    steps:
      - name: Deploy Job
        run: echo ${{ github.job }}

       
