name: Java CI with Gradle

on:
  #workflow_call:
   push:
     branches: [ "main1"] 

env:
  SNOW_URL: ${{ secrets.SNOW_URL }}
  SNOW_TOKEN: ${{ secrets.SNOW_TOKEN }}
  SNOW_TOOLID: ${{ secrets.SNOW_TOOLID }}
  PIPELINE_ID: ${{ github.run_id }}
  API_V4_URL: ${{ github.server_url }}
  JOB_ID: ${{ github.run_id }}
  PROJECT_PATH: ${{ github.job }}
  REPOSITORY_NAME: ${{ github.repository }}
  RUN_ATTEMPT: ${{ github.run_attempt }}
  PROJECT_ID: ${{ github.run_id }}
  PROJECT_TITLE: ${{github.repository}}/${{github.workflow}}
  COMMIT_BRANCH: $${{github.ref_name }}
  WORKFLOW_NAME: ${{ github.workflow }} 

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - name: Pre-Build Step
        run: echo ${{ github.job }}

  changeapproval:
    runs-on: ubuntu-latest
    container:
      image: mdavireddy/sndevops:2.0.0
    env:
      JOB_NAME: changeapproval
    steps:
      - name: Create Change Request
        run: |
          echo "CHG_JOB_ID=${{ github.run_id }}"
          sndevopscli create change -ctx "{\"projectId\": \"123456\", \"attemptNumber\": \"${{ github.run_attempt }}\"}" -p "{\"changeStepDetails\": {\"timeout\":3600,\"interval\":100},\"autoCloseChange\":true,\"attributes\":{\"short_description\":\"G Venkata Automated Software Deployment\",\"description\":\"Automated Software Deployment.\",\"assignment_group\":\"a715cd759f2002002920bde8132e7018\",\"implementation_plan\":\"Software update is tested and results can be found in Test Summaries Tab.\",\"backout_plan\":\"When software fails in production, the previous software release will be re-deployed.\",\"test_plan\":\"Testing if the software was successfully deployed or not\"}}"

  getchange:
    runs-on: ubuntu-latest
    needs: changeapproval
    container:
      image: mdavireddy/sndevops:2.0.0
    env:
      JOB_NAME: getchange   
    steps:
      - name: Get Change Request
        run: |
           echo "hello"
           sndevopscli get change -p "{\"buildNumber\":\"${{ github.run_id }}\",\"stageName\":\"changeapproval\",\"pipelineName\":\"${{github.repository}}/${{github.workflow}}\", \"attemptNumber\": \"${{ github.run_attempt }}\"}"


  
  deploy:
    runs-on: ubuntu-latest
    needs: getchange
    steps:
      - name: Deploy Job
        run: echo ${{ github.job }}
        
  ServiceNowDevOpsSonarScanResults:
      name: ServiceNowDevOpsSonarScanResults
      needs: deploy
      runs-on: ubuntu-latest
      container:
        image: mdavireddy/sndevops:2.0.0
      env:
        JOB_NAME: "ServiceNowDevOpsSonarScanResults"
      steps:
        - name: devops soanr results
          run: |
            sndevopscli create sonar -url  'https://sonarcloud.io' -projectKey 'mdavireddy_rabbitmq-demo'
      
        
  ScanResults:
    runs-on: ubuntu-latest
    needs: deploy
    container:
      image: mdavireddy/sndevops:2.0.0
    steps:
      - name: Update Change Request
        run: |
            echo "hello"
            sndevopscli create securityScan -p "{ \"pipelineInfo\": {  \"runId\": \"${{ github.run_id }}\",   \"runNumber\": \"${{ github.run_number }}\", \"runAttempt\": \"${{ github.run_attempt }}\",   \"job\": \"ServiceNowDevOpsSecurityScan\",  \"workflow\": \"${{ github.workflow }}\",  \"repository\": \"${{github.repository}}\" }, \"securityResultAttributes\": { \"scanner\": \"Veracode\",    \"applicationName\": \"PetStoreAPI-Github\",\"buildVersion\": \"\",   \"securityToolId\": \"\"}}"
