

name: SkippedPipeline

on:
  push:
    branches: [ "main" ]

jobs:
  # Stage 1: Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

  build-skipstage1:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main1'
    steps:
      - name: Deploy to Staging
        run: echo 'hello'    

  build-skipstage2:
    runs-on: ubuntu-latest
    needs: build-skipstage1
    if: github.ref == 'refs/heads/main1'
    steps:
      - name: Deploy to Staging
        run: echo 'hello'     

  build-skipstage3:
    runs-on: ubuntu-latest
    needs: build-skipstage2
    if: github.ref == 'refs/heads/main1'
    steps:
      - name: Deploy to Staging
        run: echo 'hello'  
        
  build-skipstage4:
    runs-on: ubuntu-latest
    needs: build-skipstage3
    if: always()
    steps:
      - name: Deploy to Staging
        run: echo 'hello'     

  build-skipstage5:
    runs-on: ubuntu-latest
    needs: build-skipstage4
    if: always()
    steps:
      - name: Deploy to Staging
        run: echo 'hello'
   

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build-skipstage5
    if: always()
    steps:
      - name: Deploy to Staging
        run: exit 1

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging

    if: always()
    steps:
      - name: Deploy to Production
        run: echo 'hello'



